# Start from the Isaac ROS development image
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install additional ROS packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-isaac-ros-yolov8 \
    ros-humble-isaac-ros-dnn-image-encoder \
    ros-humble-isaac-ros-tensor-rt \
    ros-humble-ros-gz \
 && rm -rf /var/lib/apt/lists/*

COPY scripts/entrypoint_orca25.sh /usr/local/bin/scripts/entrypoint_additions/
